import Head from "next/head";
import {
  Navbar,
  Hero,
  Footer,
  Solutions,
  Features,
  Banner,
  CTA,
  Aboutus,
  Questions,
  Testimonials,
} from "../components";
import Accordion from "../components/component-utils/Accordion";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next-Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Hero />
        <Banner />
        <Features />
        <CTA />
        <Aboutus />
        {/* <Questions /> */}
        <Solutions />
        {/* <Testimonials /> */}
        <Footer />
      </main>
    </div>
  );
}
